name: test
on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    name: Container with name
    runs-on: ubuntu-latest
    container: 
      image: nginx:latest
      options: >-
        --name myContainerName

    steps:
    - name: done
      run: echo "done"
