name: test
on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    name: Container with name
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/repo/image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: >-
        --name myContainerName
